### PR TITLE
Use specified threshold instead of DEFAULT_CHUNK_THRESHOLD in pickchunksize

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]
Wow..

**Comment by chriselrod** [comment]
> Wow..

Git blame says it's been like this for 4 years!

**Comment by chriselrod** [comment]
Is this test always so unreliable?
```julia
Error During Test at /home/runner/work/ForwardDiff.jl/ForwardDiff.jl/test/DualTest.jl:400
  Test threw exception
  Expression: dual_isapprox(NESTED_FDNUM ^ PRIMAL, exp(PRIMAL * log(NESTED_FDNUM)))
  DomainError with -8.830391984918102e18:
```

**Comment by KristofferC** [comment]
Yes, they are.

**Pull request merged**
