### PR TITLE
lgamma and digamma functions for typed forward diff

### PR DESCRIPTION
**Pull request by rgiordan**
Please let me know if you want me to make any additional changes.

### CODE REVIEW

**Comment by mlubin** [comment]
@jrevels, will this be addressed by #27?

**Comment by jrevels** [comment]
> @jrevels, will this be addressed by #27?

Yep! `GradientNum` already has these defined via the Calculus.jl-based generation, and I translated @rgiordan's definitions to work with the new `HessianNum` implementation [here](https://github.com/JuliaDiff/ForwardDiff.jl/commit/34378c3fc6b77803b63be553f65cc648fc12aed9). I'll want to extend these to `TensorNum` as well, but I plan to cover `AutoDiffNum` function support in a post-#27 PR so it might be a little while.

BTW, merging this into master now shouldn't make life any harder for me over in #27, so feel free to do so if you think it's worth it. 

@rgiordan Thanks for this addition, and for the accompanying tests!

**Comment by rgiordan** [comment]
Any reason this can't be merged in the meantime?  Some other people are using code in other packages based on this change, and it would be nice not to make them check out a custom branch of this package.

**Comment by mlubin** [comment]
@rgiordan, the target for merging #27 is in the next week or so, and we're limited by developer cycles

**Comment by mlubin** [comment]
There are still a number of bugs and outstanding issues with the current code which won't be fixed before #27, but okay to merge this.

**Comment by rgiordan** [comment]
@mlubin, no problem, and thanks for keeping it on the radar.

**Comment by rgiordan** [comment]
Is it possible to tag a release that includes this change but doesn't require Julia v0.4?  I've been writing a lot of models that use ForwardDiff and rely on having an lgamma function, but wasn't planning to upgrade to 0.4 yet.  It'd be nice to be able to publish them without requiring everyone to pin ForwardDiff to a specific commit number.

**Comment by mlubin** [comment]
It should be safe to tag this as 0.0.3. @jrevels?

**Comment by jrevels** [comment]
[Done](https://github.com/JuliaDiff/ForwardDiff.jl/tree/v0.0.3).

**Comment by rgiordan** [comment]
Thank you!

**Comment by rgiordan** [comment]
@jrevels, are you planning to make a pull request to METADATA.jl with the new version number?

**Comment by mlubin** [comment]
Thought that was already done

**Comment by rgiordan** [comment]
I am new to tagging releases in Julia, so I might be missing something, but after running ```Pkg.update```, 

```
julia> Pkg.pin("ForwardDiff", v"0.0.3")
ERROR: ForwardDiff – 0.0.3 is not a registered version
 in error at error.jl:21
 in pin at pkg/entry.jl:231
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in pin at pkg.jl:39
```

Also, I only see a ```v0.0.2``` folder in [METADATA.jl](https://github.com/JuliaLang/METADATA.jl/tree/5b777a48277b1aba10aaa5d09ca59346836afbd0/ForwardDiff/versions).

**Comment by jrevels** [comment]
Oh, I just thought you wanted me to tag the repo so people wouldn't have to pass around a SHA to know where to check out the relevant commit...I never registered it in METADATA. My bad. I'm about to leave to catch a train, but I can submit PR for it tomorrow (or if @mlubin has the time, he could do so).

**Comment by rgiordan** [comment]
Ok, thanks, @jrevels .  I really just want to be able to explicitly declare package dependencies, so I do need it to be in METADATA.  There's no rush though, just wanted to make sure you know that's what I'm asking for!  Tomorrow is perfectly fine.

**Comment by rgiordan** [comment]
@jrevels , any chance you have a moment to put this in METADATA.jl?

**Comment by jrevels** [comment]
...did JuliaLang/METADATA.jl#3366 not accomplish this?

**Comment by rgiordan** [comment]
Ah, sorry, I just looked in the METADATA versions folder for ForwardDiff
and didn't try to run Pkg.update().  Yes, that does it.

**Pull request merged**
