### PR TITLE
use the preference system for nan safe mode

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
Closes https://github.com/JuliaDiff/ForwardDiff.jl/issues/181 I think

**Review by devmotion — APPROVED** [review]
My knowledge about Preferences is only based on its README, but according to this it looks good to me. Seems to match the instructions in https://github.com/JuliaPackaging/Preferences.jl#conditional-loading.

**Comment by chriselrod** [comment]
How does one `@set_preferences!`?

**Comment by devmotion** [comment]
You use `set_preferences!`: https://juliadiff.org/ForwardDiff.jl/dev/user/advanced/#Fixing-NaN/Inf-Issues

**Comment by chriselrod** [comment]
```julia
julia> using ForwardDiff, Preferences

julia> set_preferences!(ForwardDiff, "nansafe_mode" => true)
```
Ah, thanks!

**Pull request merged**
