### PR TITLE
Badge fun

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by jrevels** [comment]
Thanks!

**Comment by jrevels** [comment]
Hmm. Actually, should we really be displaying the v0.3 badge if the current version only supports v0.4? (probably shouldn't have merged this so quickly).

**Comment by mlubin** [comment]
Probably better to not display it

**Comment by IainNZ** [comment]
Well it'll show the status of the last 0.3 version, which has some utility. It'll also show that the version number is older.

**Comment by felipenoris** [comment]
Is there a tagged version that supports v0.3? Also, I guess there´s an inconsistency on *METADATA.jl* entry for this package. It says that the last version is v0.0.2, and the only tagged version on this repository is the new v0.1.0, which maybe explains why http://pkg.julialang.org/?pkg=ForwardDiff&ver=0.4 shows v0.0.2 for the current version of this package.

**Comment by felipenoris** [comment]
... so , if there´s no tagged version that supports v0.3, maybe there´s no reason to show a badge for that.

**Comment by jrevels** [comment]
> Well it'll show the status of the last 0.3 version, which has some utility. It'll also show that the version number is older.

Oh okay, I thought it would just show that ForwardDiff v0.1.0 fails on Julia v0.3. It's nifty that it will just pull the last supported version (from the `REQUIRE` file, I guess?).

> Is there a tagged version that supports v0.3? Also, I guess there´s an inconsistency on METADATA.jl entry for this package. It says that the last version is v0.0.2, and the only tagged version on this repository is the new v0.1.0, which maybe explains why http://pkg.julialang.org/?pkg=ForwardDiff&ver=0.4 shows v0.0.2 for the current version of this package.

[This PR still needs to be merge before the tags will update](https://github.com/JuliaLang/METADATA.jl/pull/3272), but the old release (v0.0.2) is still available by checking out the commit.

**Comment by felipenoris** [comment]
Somehow, v0.0.2 is linked to commit 6da5f5204f.

**Comment by IainNZ** [comment]
PkgEval is really simple - it just does Pkg.add, so it'll get whatever Pkg thinks appropriate for that version (https://github.com/IainNZ/PackageEvaluator.jl/blob/221ec3e03a136619e2082ea28171cb3313cc0508/scripts/setup.sh#L137)

**Comment by IainNZ** [comment]
Oh damn you are right: https://github.com/JuliaLang/METADATA.jl/commit/54e46809310dfacbfd8e20a723960a689b5342bc
@scidom must of backdoor tagged a new release by committing directly to METADATA and changing the SHA

**Comment by jrevels** [comment]
Yup, there's no tag for any previous versions in this repo.

Won't `Pkg.add` still checkout 6da5f52 on Julia v0.3 anyway? My assumption was that versioning was tied to the SHA, not necessarily to the tag.

**Comment by felipenoris** [comment]
I would be impressed if that works.

**Comment by jrevels** [comment]
Speaking of, is there any reason I shouldn't just add the v0.0.2 tag to 6da5f52 right now? Git allows pushing new tags of older commits.

**Comment by IainNZ** [comment]
`Pkg.add` is based on METADATA only - `git` tags are for humans.

**Comment by IainNZ** [comment]
Yes that'd be nice for histories sake

**Comment by IainNZ** [comment]
Did you manually add that `0.1.0` tag manually? `Pkg.tag` will do it for you, helps keep METADATA and the package in sync

**Comment by jrevels** [comment]
> Did you manually add that 0.1.0 tag manually?

No, I tagged it with Pkg.tag

**Comment by IainNZ** [comment]
Oh sorry, I didn't see https://github.com/JuliaLang/METADATA.jl/pull/3272 (I unsubbed from METADATA)

**Comment by jrevels** [comment]
Okey dokey, I manually added the tag for v0.0.2 to this repo - should make things less confusing in the future.

> Oh sorry, I didn't see JuliaLang/METADATA.jl#3272 (I unsubbed from METADATA)

no probs

**Pull request merged**
