### PR TITLE
unrestrict chunk size

### PR DESCRIPTION
**Pull request by jrevels**
A while ago, I refactored ForwardDiff to remove all `@generated` functions from the codebase. A direct effect of this was that a bunch of elementwise functions on `Partials` had to be restricted to a small subset of chunk sizes (from `1` to `10`). Obviously, this restriction can be annoying for users who want to play around with chunk sizes greater than `10`. This PR reintroduces `@generated` functions for the affected `Partials` code, thus enabling the use of any chunk size via the API.

AFAICT after a small bit of profiling, this doesn't affect performance at all. I'll do some more benchmarking later today to confirm that, though.

Note also that I intend to tag ForwardDiff v0.3.0 after this PR gets merged.

### CODE REVIEW

**Comment by mlubin** [comment]
How's the hit on compilation time?

**Comment by KristofferC** [comment]
+1. I have found that 10 chunk size is a bit small.

**Comment by jrevels** [comment]
> How's the hit on compilation time?

There's a slight slowdown, but it doesn't seem too significant. Also, I think #137 might be at least somewhat fixed on the `master` branch of ForwardDiff now, so I suppose it's not as much of an issue?

Here's the code I'm using to check this:

```julia
using ForwardDiff, BenchmarkTools

function rosenbrock(x)
   a = one(eltype(x))
   b = 100 * a
   result = zero(eltype(x))
   for i in 1:length(x)-1
       result += (a - x[i])^2 + b*(x[i+1] - x[i]^2)^2
   end
   return result
end

out, x = zeros(100, 100), rand(100);

cfg = ForwardDiff.HessianConfig(x);

# measures compilation performance
@time ForwardDiff.hessian!(out, rosenbrock, x, cfg);

# measures runtime performance
@benchmark ForwardDiff.hessian!($out, $rosenbrock, $x, $cfg) evals=1
```

On master (showing the two lines we care about):

```julia
julia> @time ForwardDiff.hessian!(out, rosenbrock, x, cfg);
  2.081374 seconds (2.03 M allocations: 45.544 MB, 1.04% gc time)

julia> @benchmark ForwardDiff.hessian!($out, $rosenbrock, $x, $cfg) evals=1
BenchmarkTools.Trial:
  memory estimate:  87.52 kb
  allocs estimate:  11
  --------------
  minimum time:     5.263 ms (0.00% GC)
  median time:      5.271 ms (0.00% GC)
  mean time:        5.315 ms (0.13% GC)
  maximum time:     8.135 ms (33.59% GC)
  --------------
  samples:          941
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

On this branch:

```julia
julia> @time ForwardDiff.hessian!(out, rosenbrock, x, cfg);
  2.188665 seconds (2.12 M allocations: 48.981 MB, 0.84% gc time)

julia> @benchmark ForwardDiff.hessian!($out, $rosenbrock, $x, $cfg) evals=1
BenchmarkTools.Trial:
  memory estimate:  87.52 kb
  allocs estimate:  11
  --------------
  minimum time:     5.265 ms (0.00% GC)
  median time:      5.274 ms (0.00% GC)
  mean time:        5.321 ms (0.16% GC)
  maximum time:     9.114 ms (0.00% GC)
  --------------
  samples:          940
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

Using ForwardDiff v0.2.2:

```julia
julia> c = ForwardDiff.Chunk{10}();

julia> @time ForwardDiff.hessian!(out, rosenbrock, x, c);
 17.425611 seconds (2.38 M allocations: 60.944 MB, 0.21% gc time)
```

So it seems compilation times have improved significantly since #137 was filed.

**Comment by KristofferC** [comment]
Should these checks have been removed?

```jl
julia> ForwardDiff.GradientConfig{15}(rand(15))
------ AssertionError ------------------ Stacktrace (most recent call last)

AssertionError: N <= CHUNK_THRESHOLD
```

**Pull request merged**
