### PR TITLE
reduce occurences of tag errors

### PR DESCRIPTION
**Pull request by simonbyrne**
Nested differentiation can fail in cases where there are no operations involving the inner gradient, e.g.
```
ForwardDiff.derivative(1.0) do x
    ForwardDiff.derivative(x) do y
        x
    end
end
```

I'm pretty sure this is safe...

### CODE REVIEW

**Comment by jrevels** [comment]
These seem sensible to me. 

Rebase against master to get the Kristoffer's shiny new appveyor file?

> Coverage increased (+17.07%) to 88.084%

lol Coveralls.

**Comment by simonbyrne** [comment]
Are the appveyor failures expected?

**Comment by simonbyrne** [comment]
bump: any ideas what is going on here?

**Comment by jrevels** [comment]
Windows tests have been kind of broken for awhile; the tests seem more sensitive to the finite differencing error. Would be worth figuring out at some point but it's unrelated to this PR.

**Comment by simonbyrne** [comment]
can you tag a new release?

**Pull request merged**
