### PR TITLE
use `oneunit(T)` in `construct_seeds`

### LINKED ISSUE #651: `construct_seeds` for types where `typeof(one(T)) !=T` is broken
as far as i understand, the type of `one(T)` is not necessarily `T` (https://github.com/JuliaPhysics/Measurements.jl/issues/134 for example). but `construct_seeds` will use `(one(T),zero(T))`, maybe using `oneunit` there is more correct?

### PR DESCRIPTION
**Pull request by longemen3000**
should fix #651 ?

### CODE REVIEW

**Comment by longemen3000** [comment]
the invalidations tests has an unrelated error

**Comment by mcabbott** [comment]
This seems fine. Is it easy to add a test, e.g. loading the smallest / slowest-changing package which defines a number for which one != oneunit?

**Comment by longemen3000** [comment]
Measurements? and an unary function. (binary functions require defining some interactions between `ForwardDiff.Dual` and `Measurements.Measurement`, i had a package that defines some of those in https://github.com/longemen3000/ForwardDiffOverMeasurements.jl, but that is not necessary for the test).

**Comment by longemen3000** [comment]
I added Measurements.jl as an example package that has `oneunit(T) != one(T)`.

The invalidation tests fails with the `stat_rep(::Nothing)` method error, and there are errors on nightly, that i don't know if are unrelated.

**Comment by longemen3000** [comment]
replaced by #659

**Pull request closed without merging**
