### PR TITLE
Fix #270

### LINKED ISSUE #270: Spurious perturbation confusion errors with muladd
In OrdinaryDiffEq.jl, we noticed some spurious perturbation confusion errors. Essentially, we solve a DiffEq in a way that doesn't need ForwardDiff to get a continuous function `sol(t)`, and then do `ForwardDiff.derivative(sol, t)` on it in a test. But, even with no other Dual numbers involved, it errors:

```julia
potential perturbation confusion detected when computing binary operation on Dual{ForwardDiff.Tag{DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!},OrdinaryDiffEq.InterpolationData{DiffEqProblemLibrary.##1#2,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.SSPRK22ConstantCache}},0xb046287d533b082d}}(0.0,1.0) and Dual{Void}(0.5,0.0) (tag mismatch: ForwardDiff.Tag{DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!},OrdinaryDiffEq.InterpolationData{DiffEqProblemLibrary.##1#2,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.SSPRK22ConstantCache}},0xb046287d533b082d} != Void). ForwardDiff cannot safely perform differentiation in this context; see the following issue for details: https://github.com/JuliaDiff/ForwardDiff.jl/issues/83
ode_interpolant(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!},OrdinaryDiffEq.InterpolationData{DiffEqProblemLibrary.##1#2,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.SSPRK22ConstantCache}},0xb046287d533b082d},Float64,1}, ::Float64, ::Float64, ::Float64, ::Array{Float64,1}, ::OrdinaryDiffEq.SSPRK22ConstantCache, ::Void, ::Type{Val{0}}) at interpolants.jl:83
ode_interpolation(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!},OrdinaryDiffEq.InterpolationData{DiffEqProblemLibrary.##1#2,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.SSPRK22ConstantCache}},0xb046287d533b082d},Float64,1}, ::Function, ::Void, ::Type{T} where T) at generic_dense.jl:255
derivative(::DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Array{Float64,1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,DiffEqProblemLibrary.##1#2,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!},OrdinaryDiffEq.InterpolationData{DiffEqProblemLibrary.##1#2,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.SSPRK22ConstantCache}}, ::Float64) at derivative.jl:19
#regression_test#21(::Bool, ::Function, ::OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!}, ::Float64, ::Float64) at ode_dense_tests.jl:41
(::#kw##regression_test)(::Array{Any,1}, ::#regression_test, ::OrdinaryDiffEq.SSPRK22{OrdinaryDiffEq.#trivial_limiter!,OrdinaryDiffEq.#trivial_limiter!}, ::Float64, ::Float64) at <missing>:0
include_string(::String, ::String) at loading.jl:515
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##49#53{String,Int64,String})() at eval.jl:50
withpath(::Atom.##49#53{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
macro expansion at eval.jl:49 [inlined]
(::Atom.##48#52{Dict{String,Any}})() at task.jl:80
```

Somehow a tag got dropped. I am not sure yet how to reproduce it in a smaller code because I'm not sure of an easy way to create Dual numbers with tags for testing, but I tested out a few things where the error was an found very specific behavior. The error was in the small function which is simplified as:

```julia
@inline @muladd function ode_interpolant(Θ,dt,y₀,y₁,k,cache::Union{SSPRK22ConstantCache,SSPRK33ConstantCache,SSPRK432ConstantCache},idxs::Void,T::Type{Val{0}})
  (1-Θ^2) + Θ^2 + Θ
end
```

In this calculation, only `Θ` is a Dual number and the rest are `Float64`s. Now that errored, but changing it to any binary addition (for example `(1-Θ^2) + Θ^2`) fixes it. This leads me to believe that the tagging is setup to choose the right type for `+(a,b)`, but for `+(a...)` it defaults to tagging it with `Void` which causes the error since it's trying to make an array of `eltype(A) == typeof(Θ)`. 

I think that's enough to pin it down?

Ref https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/200

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Thanks to @KristofferC for pointing this out. The problem was specific to which arguments had duals, and this one dispatch was missing `{T}`.

### CODE REVIEW

**Comment by KristofferC** [comment]
Probably also for fma.

**Comment by jrevels** [comment]
Thanks!

Hmm...can't reproduce Travis failure locally. Can you add a test to the `fma`/`muladd` section at the bottom of `DualTest.jl` that would fail before this fix?

**Comment by ChrisRackauckas** [comment]
Is there some standard function for getting the type that's in the tag part of the `Dual` or should I implement a quick one on the fly there? Instead of checking values it nenew checks for just checking that the tag isn't `Void`.id`.

**Comment by ChrisRackauckas** [comment]
I added a singleton type `TestTag` to every `Dual` used in `DualTest`. Thus all of the methods would fail if tags are dropped like in the `muladd` example. This makes the DualTest.jl tests catch this problem, but also it would catch this same problem in any other arithmetic function that is tested.

And because of that, it found 4 other instances where tests fail. I labeled those as `@test_broken` and will open an issue for them to be considered separately.

**Comment by ChrisRackauckas** [comment]
Note that I can reproduce the Travis failure locally, but it is unrelated.

**Comment by jrevels** [comment]
> I added a singleton type TestTag to every Dual used in DualTest. Thus all of the methods would fail if tags are dropped like in the muladd example. This makes the DualTest.jl tests catch this problem, but also it would catch this same problem in any other arithmetic function that is tested.

Sounds great! Thanks for this.

**Pull request merged**
