### PR TITLE
enable AppVeyor

### PR DESCRIPTION
**Pull request by jrevels**
prompted by #220

### CODE REVIEW

**Comment by jrevels** [comment]
@mlubin So it looks like everything is passing here, but I'm not using `julia-debug` so that could be the difference between here and #220. Should I be using that along with/instead of the default? I'm a total noob when it comes to AppVeyor/Windows.

**Comment by mlubin** [comment]
It's worth trying ``julia-debug`` just to see if you can reproduce the issue I had. @tkelman might have some advice on which should be the default.

**Comment by jrevels** [comment]
Oh, duh - ForwardDiff master is drastically different from ForwardDiff 0.4.2, so that's probably a factor as well.

**Comment by jrevels** [comment]
I'm going to merge this for now, since it includes a bug fix for 32 bit systems.

**Pull request merged**
